image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build

before_script:
  - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD} ;fi

build:master:
  stage: build
  script:
    - docker build -t ${DOCKERHUB_REPO}:latest .
    - docker tag ${DOCKERHUB_REPO}:latest ${DOCKERHUB_REPO}:master
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker push ${DOCKERHUB_REPO}:latest; fi
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker push ${DOCKERHUB_REPO}:master; fi

build:v1.1:
  stage: build
  script:
    - docker build --build-arg GITEA_VERSION=release/v1.1 -t ${DOCKERHUB_REPO}:v1.1 .
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker push ${DOCKERHUB_REPO}:v1.1; fi
