name: Build & Push to Docker Registry

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'
  repository_dispatch:
    types: run-dockerpush

env:
  IMAGE_NAME: titouanco/gitea

jobs:
  gitea-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --build-arg GITEA_VERSION=master -t ${{ env.IMAGE_NAME }}:latest

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push ${{ env.IMAGE_NAME }}:latest

  gitea-v1_11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --build-arg GITEA_VERSION=release/v1.11 -t ${{ env.IMAGE_NAME }}:v1.11

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push ${{ env.IMAGE_NAME }}:v1.11

  gitea-v1_10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --build-arg GITEA_VERSION=release/v1.10 -t ${{ env.IMAGE_NAME }}:v1.10

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push ${{ env.IMAGE_NAME }}:v1.10